import google.generativeai as genai
import config

class GeminiService:
    def __init__(self):
        genai.configure(api_key=config.GEMINI_API_KEY)
        self.working_model = None
        self.tried_models = [
            'gemini-2.5-flash', 'models/gemini-2.5-flash',
            'gemini-2.0-flash', 'models/gemini-2.0-flash',
            'gemini-1.5-flash', 'models/gemini-1.5-flash', 
            'gemini-pro', 'models/gemini-pro'
        ]
        
    def _get_model(self):
        if self.working_model:
            return self.working_model
            
        for name in self.tried_models:
            try:
                m = genai.GenerativeModel(name)
                # Test the model with a tiny request
                m.generate_content("test")
                self.working_model = m
                print(f" [Gemini] Successfully initialized and verified model: {name}")
                return m
            except Exception as e:
                print(f" [Gemini] Attempt with {name} failed: {e}")
        
        return None

    def refine_sentence(self, noisy_text):
        """
        Refines a noisy sequence of characters and words into a meaningful sentence.
        """
        if not noisy_text or len(noisy_text.strip()) == 0:
            return ""
            
        model = self._get_model()
        if not model:
            print(" [Gemini] ERROR: No working model found. Returning raw text.")
            return noisy_text

        prompt = f"""
        You are an expert Sign Language to English translator. Your ONLY job is to take a highly distorted, poorly spelled, or noisy string of detected letters/words and output the intended, meaningful English sentence.
        
        INPUT: "{noisy_text}"
        
        RULES:
        1. The input is generated by a computer vision model that often makes mistakes like substituting "1" for "I", "az" for "am", "fie" for "fine", etc.
        2. Aggressively guess the intended meaning based on the phonetic or visual similarity of the letters.
        3. Drop completely random characters if they don't fit the sentence structure.
        4. Output the final, grammatically correct sentence and NOTHING ELSE. No explanations, no quotes.
        
        EXAMPLES:
        "H E L L L 0" -> Hello.
        "I AM 1 2 3 FINE" -> I am fine.
        "i go market 123 q q" -> I am going to the market.
        "1 az 12 fie" -> I am fine.
        "W H A T I S T I M E" -> What is the time?
        "{noisy_text}" ->
        """
        
        try:
            response = model.generate_content(prompt)
            # Handle potential safety block or empty response
            if response and response.text:
                refined = response.text.strip()
                if refined.startswith('"') and refined.endswith('"'):
                    refined = refined[1:-1]
                return refined
            return noisy_text
        except Exception as e:
            print(f" [Gemini Error] {e}")
            return noisy_text

    def refine_text_to_keywords(self, user_text):
        """
        Refines a user's text input into essential key words for Sign Language spelling.
        Removes articles, helper verbs, and filler string.
        Returns a single space-separated string of uppercase words.
        """
        if not user_text or len(user_text.strip()) == 0:
            return ""

        model = self._get_model()
        if not model:
            print(" [Gemini] ERROR: No working model found. Returning raw text upper.")
            return user_text.upper()

        prompt = f"""
        You are an expert English to ISL (Indian Sign Language) translation assistant.
        Your ONLY job is to take the user's English sentence and extract only the most essential words needed to understand the core meaning. 
        You must remove articles (a, an, the), helper verbs (is, am, are, do, does), and filler words.
        
        INPUT: "{user_text}"
        
        RULES:
        1. Return ONLY the cleaned key words as one space-separated line.
        2. DO NOT include any punctuation.
        3. The entire output MUST BE in UPPERCASE.
        4. No explanations, no quotes, just the words.
        
        EXAMPLES:
        "I want a glass of water please" -> "WANT WATER PLEASE"
        "What is the time right now" -> "WHAT TIME NOW"
        "I am going to the market" -> "GO MARKET"
        "Hello I am fine" -> "HELLO FINE"
        "{user_text}" ->
        """
        
        try:
            response = model.generate_content(prompt)
            if response and response.text:
                refined = response.text.replace('\n', ' ').strip().upper()
                # Remove quotes if generated
                if refined.startswith('"') and refined.endswith('"'):
                    refined = refined[1:-1]
                return refined
            return user_text.upper()
        except Exception as e:
            print(f" [Gemini Error text_to_keywords] {e}")
            return user_text.upper()
